-- IPTV storage schema v1
-- Canonical SQL for initial SQLite database.
-- Notes:
-- 1) Credentials should stay in secure storage. This DB stores only a key/redacted value.
-- 2) Timestamps are ISO-8601 UTC text generated by the app.

PRAGMA foreign_keys = ON;

BEGIN;

-- ------------------------------
-- Metadata and migrations
-- ------------------------------
CREATE TABLE IF NOT EXISTS schema_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  applied_at TEXT NOT NULL
);

-- ------------------------------
-- Profiles and settings
-- ------------------------------
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS profile_settings (
  profile_id TEXT PRIMARY KEY,
  subtitle_language TEXT,
  audio_language TEXT,
  watch_history_enabled INTEGER NOT NULL DEFAULT 1 CHECK (watch_history_enabled IN (0, 1)),
  autoplay_enabled INTEGER NOT NULL DEFAULT 1 CHECK (autoplay_enabled IN (0, 1)),
  updated_at TEXT NOT NULL,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

-- ------------------------------
-- Playlists and refresh config
-- ------------------------------
CREATE TABLE IF NOT EXISTS playlists (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  secure_storage_key TEXT NOT NULL,
  source_url_redacted TEXT,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_import_started_at TEXT,
  last_import_completed_at TEXT,
  last_import_staged_rows INTEGER,
  last_import_staged_duration_ms INTEGER,
  last_import_status TEXT NOT NULL DEFAULT 'never' CHECK (
    last_import_status IN ('never', 'running', 'success', 'failed')
  ),
  last_import_error TEXT
);

CREATE TABLE IF NOT EXISTS playlist_settings (
  playlist_id TEXT PRIMARY KEY,
  refresh_enabled INTEGER NOT NULL DEFAULT 1 CHECK (refresh_enabled IN (0, 1)),
  refresh_mode TEXT NOT NULL DEFAULT 'weekly' CHECK (
    refresh_mode IN ('manual', 'daily', 'every_3_days', 'weekly', 'every_2_weeks')
  ),
  refresh_interval_hours INTEGER NOT NULL DEFAULT 168 CHECK (refresh_interval_hours >= 0),
  last_refresh_at TEXT,
  next_refresh_at TEXT,
  last_refresh_status TEXT CHECK (
    last_refresh_status IS NULL OR last_refresh_status IN ('success', 'failed', 'skipped')
  ),
  updated_at TEXT NOT NULL,
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
);

-- ------------------------------
-- Content domain
-- ------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  playlist_id TEXT NOT NULL,
  provider_group_title TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  content_kind TEXT NOT NULL DEFAULT 'unknown' CHECK (
    content_kind IN ('live', 'movie', 'series', 'mixed', 'unknown')
  ),
  country_code TEXT,
  language_code TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (playlist_id, provider_group_title),
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS media_items (
  id TEXT PRIMARY KEY,
  playlist_id TEXT NOT NULL,
  content_type TEXT NOT NULL CHECK (
    content_type IN ('live', 'movie', 'episode', 'unknown')
  ),
  title TEXT NOT NULL,
  sort_title TEXT NOT NULL,
  description TEXT,
  artwork_url TEXT,
  logo_url TEXT,
  stream_url TEXT NOT NULL,
  category_id TEXT,
  group_title TEXT,
  tvg_id TEXT,
  tvg_name TEXT,
  tvg_chno TEXT,
  source_index INTEGER NOT NULL DEFAULT 0,
  provider_item_hash TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
  UNIQUE (playlist_id, stream_url, title)
);

CREATE TABLE IF NOT EXISTS series (
  id TEXT PRIMARY KEY,
  playlist_id TEXT NOT NULL,
  title TEXT NOT NULL,
  sort_title TEXT NOT NULL,
  artwork_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (playlist_id, title),
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seasons (
  id TEXT PRIMARY KEY,
  series_id TEXT NOT NULL,
  season_number INTEGER NOT NULL CHECK (season_number > 0),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (series_id, season_number),
  FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS episodes (
  id TEXT PRIMARY KEY,
  playlist_id TEXT NOT NULL,
  series_id TEXT NOT NULL,
  season_id TEXT NOT NULL,
  media_item_id TEXT NOT NULL UNIQUE,
  episode_number INTEGER NOT NULL CHECK (episode_number > 0),
  title TEXT NOT NULL,
  sort_title TEXT NOT NULL,
  artwork_url TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (series_id) REFERENCES series(id) ON DELETE CASCADE,
  FOREIGN KEY (season_id) REFERENCES seasons(id) ON DELETE CASCADE,
  FOREIGN KEY (media_item_id) REFERENCES media_items(id) ON DELETE CASCADE,
  UNIQUE (season_id, episode_number)
);

CREATE TABLE IF NOT EXISTS epg_programs (
  id TEXT PRIMARY KEY,
  playlist_id TEXT NOT NULL,
  channel_media_item_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  start_at TEXT NOT NULL,
  end_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (channel_media_item_id) REFERENCES media_items(id) ON DELETE CASCADE,
  CHECK (end_at > start_at),
  UNIQUE (channel_media_item_id, start_at)
);

-- ------------------------------
-- User state domain
-- ------------------------------
CREATE TABLE IF NOT EXISTS favorites (
  profile_id TEXT NOT NULL,
  media_item_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (profile_id, media_item_id),
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (media_item_id) REFERENCES media_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS watch_history (
  id TEXT PRIMARY KEY,
  profile_id TEXT NOT NULL,
  media_item_id TEXT NOT NULL,
  watched_at TEXT NOT NULL,
  completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1)),
  position_ms INTEGER,
  duration_ms INTEGER,
  created_at TEXT NOT NULL,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (media_item_id) REFERENCES media_items(id) ON DELETE CASCADE,
  CHECK (position_ms IS NULL OR position_ms >= 0),
  CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE TABLE IF NOT EXISTS playback_progress (
  profile_id TEXT NOT NULL,
  media_item_id TEXT NOT NULL,
  position_ms INTEGER NOT NULL CHECK (position_ms >= 0),
  duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
  updated_at TEXT NOT NULL,
  last_started_at TEXT,
  PRIMARY KEY (profile_id, media_item_id),
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (media_item_id) REFERENCES media_items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hidden_categories (
  playlist_id TEXT NOT NULL,
  category_id TEXT NOT NULL,
  profile_id TEXT,
  created_at TEXT NOT NULL,
  PRIMARY KEY (playlist_id, category_id, profile_id),
  FOREIGN KEY (playlist_id) REFERENCES playlists(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

-- ------------------------------
-- Indexes for common queries
-- ------------------------------
CREATE INDEX IF NOT EXISTS idx_profiles_default ON profiles(is_default);

CREATE INDEX IF NOT EXISTS idx_playlists_enabled ON playlists(enabled);
CREATE INDEX IF NOT EXISTS idx_playlist_settings_next_refresh ON playlist_settings(next_refresh_at);

CREATE INDEX IF NOT EXISTS idx_categories_playlist_kind ON categories(playlist_id, content_kind);
CREATE INDEX IF NOT EXISTS idx_categories_playlist_normalized ON categories(playlist_id, normalized_name);

CREATE INDEX IF NOT EXISTS idx_media_playlist_type ON media_items(playlist_id, content_type);
CREATE INDEX IF NOT EXISTS idx_media_playlist_sort ON media_items(playlist_id, sort_title);
CREATE INDEX IF NOT EXISTS idx_media_category ON media_items(category_id);
CREATE INDEX IF NOT EXISTS idx_media_tvg_id ON media_items(tvg_id);
CREATE INDEX IF NOT EXISTS idx_media_provider_hash ON media_items(provider_item_hash);

CREATE INDEX IF NOT EXISTS idx_series_playlist_sort ON series(playlist_id, sort_title);
CREATE INDEX IF NOT EXISTS idx_seasons_series_number ON seasons(series_id, season_number);
CREATE INDEX IF NOT EXISTS idx_episodes_series_season ON episodes(series_id, season_id);
CREATE INDEX IF NOT EXISTS idx_episodes_media_item ON episodes(media_item_id);

CREATE INDEX IF NOT EXISTS idx_epg_channel_start ON epg_programs(channel_media_item_id, start_at);
CREATE INDEX IF NOT EXISTS idx_epg_playlist_start ON epg_programs(playlist_id, start_at);

CREATE INDEX IF NOT EXISTS idx_favorites_media ON favorites(media_item_id);
CREATE INDEX IF NOT EXISTS idx_watch_history_profile_time ON watch_history(profile_id, watched_at DESC);
CREATE INDEX IF NOT EXISTS idx_watch_history_media_time ON watch_history(media_item_id, watched_at DESC);
CREATE INDEX IF NOT EXISTS idx_playback_progress_updated ON playback_progress(profile_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_hidden_categories_playlist_profile ON hidden_categories(playlist_id, profile_id);

-- ------------------------------
-- FTS5 for search
-- ------------------------------
CREATE VIRTUAL TABLE IF NOT EXISTS media_items_fts USING fts5(
  media_item_id UNINDEXED,
  title,
  sort_title,
  group_title,
  tokenize = 'unicode61 remove_diacritics 2'
);

-- Manual sync strategy (recommended for import pipeline):
-- 1) DELETE FROM media_items_fts
-- 2) INSERT INTO media_items_fts(...) SELECT ... FROM media_items

-- ------------------------------
-- Seed defaults for v1
-- ------------------------------
INSERT OR IGNORE INTO profiles (id, name, is_default, created_at, updated_at)
VALUES ('default', 'Default', 1, '1970-01-01T00:00:00Z', '1970-01-01T00:00:00Z');

INSERT OR IGNORE INTO profile_settings (
  profile_id,
  subtitle_language,
  audio_language,
  watch_history_enabled,
  autoplay_enabled,
  updated_at
)
VALUES ('default', NULL, NULL, 1, 1, '1970-01-01T00:00:00Z');

INSERT OR IGNORE INTO app_settings (key, value, updated_at)
VALUES
  ('show_continue_watching', 'true', '1970-01-01T00:00:00Z'),
  ('show_recently_watched', 'true', '1970-01-01T00:00:00Z'),
  ('show_favorites', 'true', '1970-01-01T00:00:00Z'),
  ('animations_enabled', 'true', '1970-01-01T00:00:00Z'),
  ('show_home_live_tv', 'true', '1970-01-01T00:00:00Z'),
  ('show_home_movies', 'true', '1970-01-01T00:00:00Z'),
  ('show_home_series', 'true', '1970-01-01T00:00:00Z');

INSERT OR REPLACE INTO schema_meta (key, value, updated_at)
VALUES ('schema_version', '1', '1970-01-01T00:00:00Z');

INSERT OR IGNORE INTO schema_migrations (version, name, applied_at)
VALUES (1, 'initial_schema_v1', '1970-01-01T00:00:00Z');

COMMIT;
